service:
  name: dx-identity-api
  org: dxcorp

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  auth:
    handler: src/resources/identity.auth
    events:
      # Login
      - http:
          method: post
          path: auth
      # Forget Password
      # Reset Password
  idVerification:
    handler: src/resources/identity.verify
  user:
    handler: src/resources/identity.user
    events:
      # Register
      - http:
          method: post
          path: user
      # Get users
      - http:
          method: get
          path: user
          authorizer: idVerification
      # Update profile
      - http:
          method: put
          path: user
  